import { StyleSheet } from 'react-native';

export const createStyles = (colors: any, isDark: boolean) => StyleSheet.create({
    tableContainer: {
        marginTop: 16,
        marginBottom: 16,
        marginHorizontal: 'auto',
        backgroundColor: colors.card,
        borderRadius: 12,
        shadowColor: isDark ? 'rgba(0, 0, 0, 0.3)' : 'rgba(0, 0, 0, 0.1)',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
        padding: 8,
        borderWidth: 1,
        borderColor: colors.border,
        alignSelf: 'center',
        width: '90%',
        maxWidth: 600,
    },
    tableRow: {
        flexDirection: 'row',
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
        minHeight: 100,
        paddingVertical: 12,
        width: '100%',
    },
    cell: {
        paddingVertical: 12,
        paddingHorizontal: 12,
        borderRightWidth: 1,
        borderRightColor: colors.border,
        justifyContent: 'center',
    },
    cellA: {
        flex: 0.6,
    },
    cellB: {
        flex: 0.4,
    },
    cellText: {
        fontSize: 14,
        lineHeight: 22,
        fontWeight: '500',
        color: colors.text,
        flexWrap: 'wrap',
        flex: 1,
    },
    editableCell: {
        minHeight: 44,
        borderWidth: 1.5,
        borderColor: colors.primary,
        borderRadius: 8,
        paddingVertical: 8,
        paddingHorizontal: 12,
        marginVertical: 4,
        justifyContent: 'center',
        backgroundColor: colors.background,
        alignItems: 'center',
        alignSelf: 'stretch',
        width: '100%',
    },
    errorContainer: {
        padding: 16,
        alignItems: 'center',
    },
    errorText: {
        fontSize: 14,
        color: 'red',
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalContent: {
        width: '80%',
        maxHeight: '80%',
        borderRadius: 12,
        padding: 16,
        backgroundColor: colors.background,
    },
    optionButton: {
        padding: 16,
        borderWidth: 1,
        borderRadius: 8,
        marginBottom: 8,
        borderColor: colors.border,
        backgroundColor: colors.card,
    },
    optionText: {
        fontSize: 16,
        textAlign: 'center',
        color: colors.text,
    },
    incorrectCell: {
        height: 44,
        borderWidth: 1,
        borderColor: '#d32f2f',
        borderRadius: 8,
        paddingVertical: 8,
        paddingHorizontal: 12,
        marginVertical: 4,
        justifyContent: 'center',
        backgroundColor: '#ffebee',
        alignSelf: 'flex-start',
        width: '90%',
    },
    incorrectText: {
        fontSize: 14,
        lineHeight: 20,
        color: '#d32f2f',
        flexWrap: 'wrap',
    },
    correctCell: {
        height: 44,
        borderWidth: 1,
        borderColor: '#388e3c',
        borderRadius: 8,
        paddingVertical: 8,
        paddingHorizontal: 12,
        marginVertical: 4,
        justifyContent: 'center',
        backgroundColor: '#e8f5e9',
        alignSelf: 'flex-start',
        width: '90%',
    },
    correctText: {
        fontSize: 14,
        lineHeight: 20,
        fontWeight: '600',
        color: '#388e3c',
        flexWrap: 'wrap',
    },
    successModalContent: {
        width: '80%',
        maxWidth: 300,
        padding: 24,
        borderRadius: 16,
        alignItems: 'center',
        elevation: 5,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        backgroundColor: colors.card,
    },
    successTitle: {
        fontSize: 24,
        fontWeight: 'bold',
        marginTop: 16,
        marginBottom: 8,
        color: colors.text,
    },
    pointsText: {
        fontSize: 18,
        color: '#4CAF50',
        fontWeight: '600',
    },
    explanationText: {
        fontSize: 14,
        lineHeight: 20,
        color: colors.text,
        fontStyle: 'italic',
        opacity: 0.8,
        marginTop: 8,
        paddingTop: 8,
        borderTopWidth: StyleSheet.hairlineWidth,
        borderTopColor: colors.border,
        flexWrap: 'wrap',
    },
}); 